import logging
from typing import Optional, List
from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from sqlalchemy import desc

from app.database import get_db
from app.models.alert import Alert
from app.schemas.alert import AlertResponse, AlertListResponse

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/alerts", tags=["Alerts"])


@router.get(
    "",
    response_model=AlertListResponse,
    summary="Fetch live AML alert notifications",
    description="Returns latest alerts generated by the live transaction listener and heuristic flagging engine."
)
def get_alerts(
    severity: Optional[str] = Query(None, description="Filter by severity: critical, high, medium, low"),
    limit: int = Query(50, ge=1, le=200, description="Max alerts to return"),
    db: Session = Depends(get_db)
):
    query = db.query(Alert)
    if severity and severity.upper() != "ALL":
        query = query.filter(Alert.severity == severity.lower())

    total = query.count()
    alerts = query.order_by(desc(Alert.id)).limit(limit).all()

    return AlertListResponse(total=total, alerts=alerts)
