from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class CopilotQueryRequest(BaseModel):
    address: str = Field(..., description="Target Ethereum wallet address for forensic analysis")
    question: str = Field(..., description="Investigator question or analytical inquiry")
    conversation_history: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Optional recent conversation history between user and assistant"
    )


class CopilotQueryResponse(BaseModel):
    text: str = Field(..., description="Forensic analysis response generated by the Copilot")
    grounded_on: Dict[str, Any] = Field(
        default_factory=dict,
        description="Evidentiary summary of on-chain telemetry, flags, and attribution used to ground the response"
    )
